### ISSUE TITLE
error: /dev/null - Success

### ISSUE THREAD

**Issue by jwilk** [bindh3x/libnicko#2]
```console
$ nicko /dev/null
error: /dev/null - Success
```
So is it error or success?

**Comment by bindh3x** [comment]
LOL sorry for that it's because of `strerror()`. I am working on a fix right now.

Thanks for catching this!

**Comment by bindh3x** [comment]
@jwilk  Can you confirm before we will close this?

**Comment by jwilk** [comment]
I'm still getting the same error for regular empty files:
```console
$ cp /dev/null empty
$ nicko empty
error: empty - Success
```

**Comment by bindh3x** [comment]
Empty files are with size of 0, so it's easy to fix.
But I think we need to write a function to identify text (utf/data) files,
and not only binaries.

I will try fix it tomorrow (when I will have more time) sorry.

Thanks for the help.

**Comment by jwilk** [comment]
Also happens with other file sizes:
```console
$ for i in $(seq 1 1000); do printf "%${i}d" > foo$i; done
$ nicko foo*
error: foo1 - Success
error: foo2 - Success
error: foo3 - Success
error: foo510 - Success
error: foo511 - Success
```
The root cause seems to be that you treat short reads as errors, even though they are not.
Now, there's already some code that looks like a defense against short reads:
```c
if ((size_t)list[i].offset > size || list[i].size > size)
  continue;
```
But this is not checked for the first read, only for subsequent ones.
And the condition is wrong; it should be something like this:
```c
list[i].offset + list[i].size > size
```

Also note that you leak file descriptor when reading fails.

**Comment by bindh3x** [comment]
@jwilk Now it's fixed (in the last 4 commits) can you please verify on your side?
I tested it,  but I be happier if you verify this.

Thanks.

**Comment by jwilk** [comment]
```console
$ for i in $(seq 1 1000); do printf "%${i}d" > foo$i; done
$ nicko foo*
foo1: zip
foo2: zip
foo3: zip
foo510: mbr
foo511: mbr
```
These still aren't correct answers.

**Comment by bindh3x** [comment]
Hi @jwilk.

OK I think it's finally fixed in https://github.com/bindh3x/libnicko/commit/6b0ecc6be5882a04303a7ec06a8905af1ec11f4b.

Thank you for reaching out and helping with this.

**Comment by jwilk** [comment]
None of the commits so far address the root cause… :-/

Short reads can still happen, and you still treat them as errors.

The errno check added in 6b0ecc6be5882a04303a7ec06a8905af1ec11f4b is unsound. This is what [the errno manpage](http://man7.org/linux/man-pages/man3/errno.3.html) says:

>The value in errno is significant only when the return value of the call indicated an error (i.e., -1 from most system calls; -1 or NULL from most library functions); a function that succeeds *is* allowed to change errno. The value of errno is never set to zero by any system call or library function.

And this check makes another error you introduced in the same commit less visible:

```console
$ nicko /nonexistent /etc/fstab 
error: /nonexistent - No such file or directory
error: /etc/fstab - No such file or directory
```
(But /etc/fstab definitely exists on this system…)

**Comment by bindh3x** [comment]
@jwilk Sorry for the late response.

OK. we are almost getting there. :smile:
The `errno` "hack" in `error()` is a temporary fix. (I failed to mention this :disappointed:)
I have a solution in mind, but I need to think about it more thoroughly.
